@startuml
== Процесс онлайн-перевода между счетами ==

actor "Клиент" as client
participant "Мобильное приложение" as app
participant "Бэкенд" as back
database "База данных" as db
participant "СМС-сервис" as sms

client -> app ++ : Инициирует перевод (сумма, получатель)
app -> back ++: Запрос на перевод (сумма, получатель)


    back -> db ++: Проверить баланс отправителя
    
    db --> back --: Результат проверки
    
    
    alt Баланс подтвержден
        par Перевод средств
            back ->> db ++: Снять средства с отправителя        
            back ->> db: Зачислить средства получателю
        end

        db --> back --: Подтверждение операций        
        
        opt Подключены уведомления по sms
            back -> sms ++ : Запрос на отправку уведомления            
            sms --> back -- : Подтверждение отправки
        end        
        
        back --> app: Успешный перевод
    else Баланс недостаточен
        back --> app -- : Ошибка: Недостаточно средств
    end

app --> client -- : Отобразить результат

@enduml