@startuml

title Процесс отправки email-рассылки

start
:Пользователь формирует письмо;
if (Проверка валидности email?) then (да)
  :Создать объект Email;
  :Добавить письмо в очередь;
  fork
    :Основной поток:;
    while (Есть письма в очереди?) is (да)
      :Взять следующее письмо;
      :Подключиться к SMTP-серверу;
      if (Успешное подключение?) then (да)
        :Отправить письмо;
        :Пометить как "Отправлено";
      else (нет)
        :Пометить как "Ошибка";
        :Записать в лог ошибку;
      endif
    endwhile
  fork again
    :Фоновый поток:;
    repeat
      :Очищать очередь от отправленных;
    repeat while (Раз в час) or (Очередь пуста?)
  end fork
else (нет)
  :Вернуть ошибку "Невалидный email";
endif

stop

@enduml
