@startuml

title Процесс оформления заказа

|Клиент|
start
:Регистрация/авторизация;
|Система|
:Проверка учетных данных;
|Клиент|
:Выбор товаров, добавление в корзину;

|Клиент|
if (Есть промокод?) then (Нет)  
else (Да)
  |Клиент|  
  :Ввод промокода;
  |Система|
  :Проверка условий использования скидки;
  if (Промокод валидный?) then (Нет)
    |Система|
    :Фиксация причины ошибки применения кода:
    1. Неверный промокод
    2. Превышение лимита на использование промокода
    3. Промокод не действует на выбранные товары;
    |Клиент| 
    :Уведомление об ошибки промокода с указанием причины;
  else (Да)
    |Система|
    :Обновление суммы заказа с учётом скидки;
  endif
endif

|Клиент|
:Оформление заказа (доставка, оплата);\

|Система|
:Проверка наличия товара;
repeat
  -> по каждому товару;
  if (Товар доступен?) then (Нет)
    |Клиент|
    :Уведомление о недоступности;
    :Выбор действия:
    1. Альтернативный товар
    2. Удалить товар;       
  else (Да)
    |Система|
    :Подтверждение наличия;
  endif
    repeat while (Все товары проверены и доступны?) is (Нет)
  
fork
  |Клиент|
  :Выбор способа оплаты;
  |Система|
  :Проверка платёжных деталей и проведение транзакции;
  if (Оплата успешна?) then (Нет)
    |Система|
    :Фиксация причины отказа платежа:
    1. Недостаточно средств
    2. Неверные платёжные данные
    3. Платёжная система недоступна;
    |Клиент|
    :Уведомление об ошибке с указанием причины;
    :Предложение альтернативы:
    1. Повтор операции
    2. Изменить способ оплаты
    3. Возможность связаться со службой поддержки;
    |Система|
    if (Клиент согласен?) then (Нет)      
      :Отмена заказа;
      :Возврат средств (если были списаны);
      stop
    else (Да)
      :Повторная попытка оплаты;
    endif    
  else (Да)
    |Система|
    :Фиксация платежа;
  endif
fork again
  |Система|
  :Обновление статуса = "Комплектация заказа";
fork again
  |Склад|
  :Уведомление о необходимости собрать заказ;
  :Подготовка товара;
  :Комплектация заказа;
|Система|
end fork

|Система|
if (Оплата и подготовка успешны?) then (Нет)
  |Система|
  :Отмена заказа;
  :Возврат средств (если были списаны);
  |Клиент|
  :Уведомление об ошибке с указанием причины;
  stop
else (Да)
  |Система|
  fork    
    :Генерация счета-фактуры;
  fork again
    |Склад|
    :Отправка заказа;
    |Система|
    :Обновление статуса = "Отправлен";
  end fork
  |Клиент|
  :Уведомление о подтверждении заказа и статусе доставки;
  :Отслеживание доставки;
  stop
  
endif

@enduml