@startuml
state "**Жизненный цикл банковской карты**" as title {

  [*] --> Неактивная : [Оформление договора]

  state Активная {
    [*] --> Обычная : [Активация через терминал]
    Премиум --> Обычная : [Отмена подписки]
        Обычная --> Премиум : [Подписка на\nпремиум пакет]
  }

  Неактивная --> Активная  
  Заблокированная --> Активная : [Мошенничество предотвращено]\n[Карта найдена]
  Активная --> Заблокированная : [Попытка мошенничества]
  Активная --> Просроченная : [Истечение срока действия]
  Активная --> Утерянная : [Заявление об утере]
  Утерянная --> Заблокированная : [Подтверждение утери]
  Просроченная --> [*] : [Уничтожение карты]
  Заблокированная --> [*] : [Блокировка более 180 дней]
}

@enduml